### ISSUE TITLE
[Suggestion] Add config to disable ore generation

### ISSUE THREAD

**Issue by SomeRandomPetey** [Droog71/Prospect-Mod#2]
In my custom pack, I'm using a different mod to generate ores but I can't disable this mod's ore gen in the config. Would be nice if that were an option.

**Comment by Droog71** [comment]
Thanks for the suggestion. This has been implemented. https://github.com/Droog71/Prospect-Mod/commit/03777a3489daca78d5b623fdcb01c62b71161bcf
